### ISSUE TITLE
vite Compliation error on `sanity/structure` 

### ISSUE THREAD

**Issue by Jamiewarb** [SimeonGriggs/sanity-plugin-utils#30]
**Description of error**

There's an open PR here: https://github.com/sanity-io/sanity-plugin-documents-pane/issues/64

It mentions an issue with `sanity-plugin-utils`. They say they think that where `sanity/structure` is used, the package should be `@sanity/structure`, in this file:

https://github.com/SimeonGriggs/sanity-plugin-utils/blob/main/src/hooks/useOpenInNewPane.tsx#L3

I'm not sure if that's the correct resolution or not. I had a look at changing the package to `@sanity/structure`, but that didn't seem to be the right fix

**Which versions of Sanity are you using?**

3.21.3

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

Node: 18.17.1
npm: 10.2.5
pnpm: 8.14.0

Error message

sanity:dev:   The plugin "vite:dep-pre-bundle" was triggered by this import
sanity:dev: 
sanity:dev:     ../../node_modules/.pnpm/sanity-plugin-utils@1.6.4_@sanity+ui@2.0.0_react-dom@18.2.0_react-fast-compare@3.2.2_react@18_dl6nsyrbpmk4iah6t67kasu2im/node_modules/sanity-plugin-utils/lib/index.esm.js:5:30:
sanity:dev:       5 │ import { usePaneRouter } from 'sanity/structure';
sanity:dev:         ╵                               ~~~~~~~~~~~~~~~~~~
sanity:dev: 
sanity:dev: 3:56:38 AM [vite] error while updating dependencies:
sanity:dev: Error: Build failed with 2 errors:
sanity:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Missing "./structure" specifier in "sanity" package
sanity:dev: ../../node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Missing "./structure" specifier in "sanity" package

**Comment by SimeonGriggs** [comment]
[Replied on the linked issue](https://github.com/sanity-io/sanity-plugin-documents-pane/issues/64)

**Comment by Jamiewarb** [comment]
Upgrading to the latest version of Sanity fixed this. Thanks for the assist Simeon
