### ISSUE TITLE
`useProjectUsers()` sets error object as users array on API failture

### ISSUE THREAD

**Issue by derweili** [SimeonGriggs/sanity-plugin-utils#33]
When the Sanity API returns an error, the error object passed to `setUsers()` resulting in the hook to return a error object, which does not comply with the typing of the function.

https://github.com/SimeonGriggs/sanity-plugin-utils/blob/004cccf227b7d823d081489dea729bd0dfb77967/src/hooks/useProjectUsers.tsx#L53-L69

Other projects/packages relying on the function and its return types defined by typescript will break. 
E.g. the workflow plugin that tries to loop over the returned users, which is not possible because on the error object. This crashes the whole plugin. ([see here](https://github.com/sanity-io/sanity-plugin-workflow-example/blob/6c9692d23a8b3d00bb995ef0242aebcf9c4a4052/src/components/WorkflowTool.tsx#L241-L242))
## Steps to replicate

1. Use the hook
2. Let the request fail (e.g. by blocking or mocking the url in browser dev tools)
3. Verify the value returned from the hook, it is now a error object which does not align with typescript types.

## Expected behavior
I would expect that the function returns an empty array on any failture

## How to fix 
In the catch block, log the error to the console but instead of returning the error, return an empty array.

https://github.com/SimeonGriggs/sanity-plugin-utils/blob/004cccf227b7d823d081489dea729bd0dfb77967/src/hooks/useProjectUsers.tsx#L66

Additionally, the typings could be improved, no not rely in implicit typing too much.

**Comment by SimeonGriggs** [comment]
There was a brief issue with this API which was the reason for the crash, which has now been resolved. I'd accept a PR for this update.
